name: pocketoptimizer
channels:
  - conda-forge
  - defaults
  - ostrokach
  - omnia
  - acellera
  - bioconda
  - oddt
  - psi4
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - acemd3=3.3.0
  - alsa-lib=1.2.3.2
  - ambertools=22.0
  - anaconda-client=1.8.0
  - anyio=3.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - attr=2.5.1
  - attrs=21.4.0
  - babel=2.10.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bhmm=0.6.3
  - biopython=1.79
  - bleach=5.0.0
  - blosc=1.21.1
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.5.18.1
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - clyent=1.2.2
  - colorama=0.4.4
  - cryptography=37.0.2
  - cudatoolkit=11.7.0
  - curl=7.83.1
  - cycler=0.11.0
  - cython=0.29.30
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - deeptime=0.4.2
  - defusedxml=0.7.1
  - dill=0.3.5.1
  - entrypoints=0.4
  - et_xmlfile=1.0.1
  - executing=0.8.3
  - expat=2.4.8
  - ffevaluation=0.1.8
  - fftw=3.3.10
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.10.4
  - gettext=0.19.8.1
  - giflib=5.2.1
  - greenlet=1.1.2
  - gst-plugins-base=1.20.2
  - gstreamer=1.20.2
  - h5py=3.6.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - htmd=2.0.5
  - htmd-deps=2.0.5
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.7.1
  - ipykernel=6.13.0
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - jack=1.9.18
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jobqueues=0.8.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.6.0
  - jupyter_client=7.3.1
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyter_server=1.17.0
  - jupyterlab=3.4.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.14.0
  - jupyterlab_widgets=1.1.0
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.64
  - libcblas=3.9.0
  - libclang=14.0.4
  - libclang13=14.0.4
  - libcups=2.3.3
  - libcurl=7.83.1
  - libdb=6.2.32
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.3.4
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.70.2
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.4
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.3
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libudev1=249
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzip=1.8.0
  - libzlib=1.2.12
  - llvmlite=0.38.1
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mdtraj=1.9.7
  - mistune=0.8.4
  - mmcif_pdbx=2.0.0
  - mmtf-python=1.1.2
  - moleculekit=1.2.2
  - msgpack-python=1.0.4
  - msmtools=1.2.6
  - multiprocess=0.70.13
  - munkres=1.1.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - natsort=8.1.0
  - nbclassic=0.3.7
  - nbclient=0.6.4
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf-fortran=4.5.4
  - networkx=2.8.2
  - nglview=3.0.3
  - nomkl=1.0
  - notebook=6.4.11
  - notebook-shim=0.1.0
  - nspr=4.32
  - nss=3.78
  - numba=0.55.1
  - numexpr=2.8.0
  - numpy=1.21.6
  - ocl-icd=2.3.1
  - ocl-icd-system=1.0.0
  - openbabel=3.1.1
  - openjpeg=2.4.0
  - openmm=7.7.0
  - openpyxl=3.0.9
  - openssl=1.1.1o
  - packaging=21.3
  - packmol=20.010
  - pandas=1.4.2
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parmed=3.4.3
  - parso=0.8.3
  - pathos=0.2.9
  - pcre=8.45
  - pdb2pqr=3.4.1
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.1.1
  - pint=0.19.2
  - pip=22.1.2
  - pixman=0.40.0
  - plumed2=2.3.3+htmd.4
  - pox=0.3.1
  - ppft=1.7.6.5
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - prompt_toolkit=3.0.29
  - propka=3.4.0
  - protocolinterface=0.4.4
  - psfgen=1.6.9
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - pycairo=1.21.0
  - pycparser=2.21
  - pyemma=2.5.11
  - pygments=2.12.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.9
  - pytz=2022.1
  - pyyaml=6.0
  - pyzmq=23.1.0
  - qt-main=5.15.3
  - rdkit=2022.03.2
  - readline=8.1
  - reportlab=3.5.68
  - requests=2.27.1
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - send2trash=1.8.0
  - setuptools=62.3.2
  - sip=6.5.1
  - six=1.16.0
  - smina=2020.12.10
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlalchemy=1.4.37
  - sqlite=3.38.5
  - stack_data=0.2.0
  - terminado=0.15.0
  - threadpoolctl=3.1.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.2.2.post1
  - tzdata=2022a
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - vina=1.2.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - weblogo=3.7.11
  - websocket-client=1.3.2
  - wheel=0.37.1
  - widgetsnbextension=3.6.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - amberlite==22.0
    - amberutils==21.0
    - mmpbsa-py==16.0
    - packmol-memgen==1.2.3rc0
    - pdb4amber==22.0
    - pytraj==2.0.6
    - sander==22.0
